edition = "2021"
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
normalize_doc_attributes = true
max_width = 80
imports_granularity = "Module"
group_imports = "StdExternalCrate"
enum_discrim_align_threshold = 40
format_strings = true
format_macro_bodies = true
wrap_comments = true
